name: Despliegue Practica
on:
  push:
    branches:
      - main  # Se activa cuando subes algo a la rama principal
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name:  Obteniendo archivos de GitHub
        uses: actions/checkout@v3

      - name:  Subiendo al Hosting AwardSpace
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Esta es la ruta de tu carpeta en el hosting
          server-dir: /walid2007.atwebpages.com/
